name: deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          yarn
          yarn ember build --environment=production
      # -
      #   name: Deploy
      #   if: success()
      #   uses: crazy-max/ghaction-github-pages@v1
      #   with:
      #     target_branch: gh-pages
      #     build_dir: dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: deploy
      #   if: success()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
