name: deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwjblue/setup-volta@v1

      -
        name: Build
        run: |
          yarn
          yarn ember build --environment=production
          cp dist/index.html dist/404.html
      # -
      #   name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: dist
      -
        name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: 'dist/'
          GH_PAT: ${{ secrets.GH_PAT }}
